hmcc-global/hmcchk-web

- server/api/controllers/auth/post-login.js
- server/api/controllers/auth/post-signup.js
- server/api/responses/unauthorized.js
- server/config/routes.js
- server/package-lock.json
- server/package.json
- ui/src/components/MainContainer.js
- ui/src/components/auth/LoginContainer.js
Basic signup and login functionality works. Need to hook it up with the model/db once that is merged in.
TODO: email verification
> 8 feature login token management

- ui/src/components/MainContainer.js
- ui/src/components/events/EventCard.js
- ui/src/components/events/EventsPage.js
- ui/src/components/helpers/eventsHelpers.js
Added functionality for add to calendar. Changed UI sizes. Mobile Views.
> 58 events page

- server/config/custom.js
- server/package-lock.json
- ui/src/components/events/EventsPage.js
- ui/src/components/helpers/eventsHelpers.js
bugfix for events page to allow PM times.
> 58 events page patch

- server/api/controllers/forms/get-form.js
- server/api/controllers/forms/post-create-submission.js
- server/api/models/Form.js
- server/config/policies.js
- ui/package-lock.json
- ui/package.json
- ui/src/components/MainContainer.js
- ui/src/components/forms/Form.js
- ui/src/components/forms/FormCreator.js
- ui/src/components/forms/FormManager.js
- ui/src/components/forms/UserFormContainer.js
- ui/src/components/helpers/userInformationHelpers.js
- ui/src/components/userProfile/UserProfileDesktop.js
- ui/src/components/userProfile/UserProfileMobile.js
> GH-108: implementation of no login user forms

- server/api/controllers/forms/post-create-submission.js
- ui/package-lock.json
- ui/package.json
- ui/public/index.html
- ui/public/manifest.json
- ui/src/components/MainContainer.js
- ui/src/components/forms/Form.js
- ui/src/components/helpers/ScrollToTop.js
Changelog
- Changed metadata and favicon for links
- Scroll to top of page on navigation
> GH-89 + GH-83: fixed link metadata, added ScrollToTop behavior on nav

- ui/src/components/AdminContainer.js
- ui/src/components/admin/AdminForm.js
> fix form manager connection

- ui/src/components/connect/OurMinistries.js
> GH-184: fixing typo again

- server/views/emails/form-retreat-success.ejs
> retreat email content fix

- ui/src/components/MainContainer.js
- ui/src/components/retreat/resources/ResourcesContainer.js
- ui/src/components/retreat/retreatTheme.js
this is done, but the resources links are all just temporary
> 215 resources page

- ui/src/components/easter/hero/HeroContainer.js
Watch Easter Video Button Enabled and Because___ Trailer Modal
> 273 hero section

- ui/src/components/easter/EasterBanner.js
> 307 banner

- ui/src/components/visit-us/Faq.js
- ui/src/components/visit-us/VisitUsPage.js
https://user-images.githubusercontent.com/33675629/163861416-467f21b5-b06a-42f7-8ad6-5591b25fd874.mp4
Took out online restrictions from the FAQ and the church in person is back.
Checked commit too
> GH-371-visitPage-welcome-back-update

- ui/src/components/visit-us/VisitUsPage.js
Changed:
link: https://bit.ly/hmcc-sc-registration
to
link: href="https://bit.ly/hmcc-sc
> QUICKFIX: Visit-Us SC Sign Up link Edit

- server/api/controllers/whitelist/get-whitelist.js
- server/api/controllers/whitelist/post-create-whitelist.js
- server/api/controllers/whitelist/post-update-whitelist.js
- server/api/helpers/auth/verify-jwt.js
- server/api/models/Whitelist.js
- server/config/routes.js
- ui/src/components/AdminContainer.js
- ui/src/components/admin/AdminWhitelistManager.js
- ui/src/components/admin/navigation/Sidebar.js
- ui/src/components/helpers/PrivateRoute.js
- ui/src/components/ignite/NoAccess.js
hardcoded for ignite right now
> 392 content restriction

- ui/src/components/about/AboutUsContainer.js
- ui/src/components/forms/Form.js
Fix bug where required radio buttons don't have proper verification enabled. Additionally added hyperlink for HMI under about
> GH-411 fix form bugs

- ui/package.json
- ui/src/components/forms/Form.js
- ui/src/components/forms/FormEditor.js
- ui/yarn.lock
Included birthday and ministry team to list of prefillable fields
> 412 Expand Prefillable Fields

- server/api/controllers/forms/post-create-submission.js
Handled both null and "" because sometimes the value cannot be set to null due to it being a required field
> GH-414: Directly update empty user information via form submission

- ui/src/components/helpers/userInformationHelpers.js
- ui/src/components/userProfile/UserProfileDesktop.js
- ui/src/components/userProfile/UserProfileMobile.js
1. Restyled header
2. Added signup links
3. Minor design changes
> GH-472: Restyled profile page, available signup forms list

- server/api/controllers/witness/get-witness-videos.js
- server/api/helpers/announcements/get-announcements.js
- server/api/helpers/witness/get-witness-videos.js
- server/config/custom.js
- server/config/policies.js
- server/config/routes.js
- Added route for witness video query
- Modified announcements query to only return posts with category: announcement
> GH-542: Witness Video Base API

- ui/src/components/MainContainer.js
- ui/src/components/events/EventCard.js
- ui/src/components/helpers/parseDescription.js
- ui/src/components/witness/WitnessContainer.js
- ui/src/components/witness/video-testimony/FilterVideos.js
- ui/src/components/witness/video-testimony/VideoCard.js
- ui/src/components/witness/video-testimony/VideoCardList.js
- ui/src/components/witness/video-testimony/VideoDetails.js
- ui/src/components/witness/video-testimony/VideoTestimonyContainer.js
- Created Video Details page
- Moved a parse description utility function used on "EventCard"
- Updated design
> GH-530: Added video details page

- server/config/policies.js
- ui/src/components/harvest-games/HarvestGamesPage.js
- Fixed API permissions for the public leaderboard
> GH-559: Harvest Games 2022 Live Leaderboard

- server/api/controllers/harvestGames/update-hg-rankings.js
- ui/src/components/events/EventCard.js
- ui/src/components/harvest-games/HarvestGameInstructions.js
- ui/src/components/harvest-games/HarvestGamesPage.js
- ui/src/components/harvest-games/styles.css
Done with the instructions, but haven't filled in the materials, and points.
> Hg instructions

- ui/src/components/harvest-games/HarvestGameInstructions.js
Fixed some errors and change the rounds and player.
> GH-583: Fixed probs & change some

- server/api/controllers/mailingList/create-mail-entry.js
- server/api/controllers/mailingList/get-mail-entry.js
- server/api/models/MailingListEntry.js
- server/config/policies.js
- server/config/routes.js
- ui/src/components/home/HomeContainer.js
- ui/src/components/home/MailingListForm.js
expected behavior:
- similar to a popup where it will show up when the home page is rendered. 
- will not show up if there is a popup that is published to  avoid conflict
- hence we can just create a popup to remove the signup form for mailing list
- text and image placeholders are there but can be added
> GH-636: mailing list form

- server/views/emails/email-retreat-payment-success.ejs
- server/views/emails/form-retreat-success.ejs
- ui/src/components/admin/forms/AdminFormDataViewer.js
- ui/src/components/forms/FormEditorContainer.js
I changed EJS content of Retreat First Email and Payment ACK email.
> GH-647:Changed Retreat First Email and Payment Acknowledgement Email

- ui/src/components/missions-month/MissionsMonthTabs.js
> MM-update for week3

- server/api/controllers/mailingList/create-mail-entry.js
- server/api/models/MailingListEntry.js
- ui/src/components/advent/AdventContainer.js
- ui/src/components/home/HomeContainer.js
- ui/src/components/home/MailingListForm.js
- added popup image & additional field fullname
- added popup to advent page
> 669 advent popup

- ui/src/components/missions-month/MissionsMonthTabs.js
Added link and prayer guide for week 4 to Mission Month.
> Added link and prayer guide

- ui/src/components/givingTuesday/GivingTuesdayPage.js
> GH-681: changed

- ui/src/components/givingTuesday/GivingTuesdayPage.js
> GH-681:deleted console

- ui/src/components/givingTuesday/GivingTuesdayPage.js
> 681 gt extend time

- ui/src/components/witness/home-sections/EasterHomeTextSection.js
> GH-723: change time format

- ui/src/components/easter-2023/CuratorWidget.js
- ui/src/components/easter-2023/Easter2023Container.js
- ui/src/components/easter-2023/EasterIGEmbed.js
> 718 easter theme page

- server/views/emails/email-ignite-payment-success.ejs
- server/views/emails/form-ignite-success.ejs
- ui/src/components/forms/FormEditorContainer.js
- success registration
- payment confirmation
> !gnite forms and emails

- server/views/emails/form-ignite-success.ejs
> changed ignite link

- server/api/controllers/forms/get-form.js
- server/api/helpers/datetime/get-offsetted-time.js
- server/api/models/Form.js
- ui/src/components/forms/ExternalFormEditor.js
- ui/src/components/forms/FormEditor.js
- ui/src/components/forms/FormEditorContainer.js
- ui/src/components/forms/FormManager.js
- ui/src/components/helpers/userInformationHelpers.js
- ui/src/components/userProfile/UserProfileContainer.js
Enable externally linked forms
> GH-769: Enable External Forms

- server/api/controllers/announcements/admin-get-announcements.js
- server/api/controllers/announcements/create-announcements.js
- server/api/controllers/announcements/get-announcements-new.js
- server/api/models/Announcement.js
- server/config/routes.js
only created Get and Create Announcements API. making PR for urgent testing needed with other branches
> Model and APIs for events/announcements

- CODEOWNERS
> GH-822: update codeowners

- ui/src/components/ripple-out/RippleOutContainer.js
- ui/src/components/ripple-out/RippleOutSpaceSection.js
> GH-817: Center image

- server/api/controllers/fundraise/admin-get-fundraise.js
- server/api/controllers/fundraise/create-fundraise.js
- server/api/controllers/fundraise/update-fundraise.js
- ui/src/components/MainContainer.js
- ui/src/components/admin/fundraise/AdminFundraiseContainer.js
- ui/src/components/admin/fundraise/AdminFundraiseGrid.js
- ui/src/components/admin/navigation/Sidebar.js
> GH-829: admin fundraising page

- server/api/controllers/faq/create-faq.js
- server/api/controllers/faq/get-faq.js
- server/api/controllers/faq/update-faq.js
- server/api/models/Faq.js
- ui/src/components/MainContainer.js
- ui/src/components/admin/faqs/AdminFaqContainer.js
- ui/src/components/admin/faqs/FaqGrid.js
- ui/src/components/admin/navigation/Sidebar.js
- Added an admin management page for FAQs
> GH-816: Admin FAQ Management Page

- ui/src/components/admin/fundraise/AdminFundraiseContainer.js
sorry randall, i was playing around and accidentally deleted your commit lol
> GH-829: lol

- ui/src/components/ripple-out/RippleOutGivingCard.js
- ui/src/components/ripple-out/RippleOutSupportGiveSection.js
change text in bank transfer card to clearly indicate ripple out remarks
> GH-844: giving card content update

- ui/src/components/ripple-out/ProgressBar.js
- ui/src/components/ripple-out/ProgressSection.js
> GHG-844: Add percentage to progress bar and rename headers

- ui/src/components/NavigationBar/MainMenu.js
pr to master since this looks like it wasn't introduced by our release and affects our main branch too
> GH-874: white buttons

- ui/src/components/ripple-out/RippleOutStoryContainer.js
- Adjusted header positioning to be synced with other pages
- Adjusted positioning of carousel arrows for larger phones
> GH-892: ROC The Story Fixes

- ui/src/components/ripple-out/RippleOutStepsContainer.js
> GH-883:  ROC The Steps Fixes

- ui/src/components/ripple-out/RippleOutSpaceContainer.js
- Increased tooltip sizes
- Increased font size for Crocodile Centre
- Adjusted tooltip positioning
> GH-884: ROC The Space Fixes

- ui/src/components/ripple-out/RippleOutSpaceContainer.js
does this looks ok? lol kinda funny
> 886: add new line for desc

- ui/src/components/connect/ExperienceHmcc.js
> GH-905: inherit color

- ui/src/components/events/EventCard.js
- ui/src/components/home/HeroSection.js
- ui/src/components/visit-us/VisitUsPage.js
- ui/src/setupProxy.js
> GH-1: Update location to TCenter

- ui/public/assets/brp_year_one.json
- ui/public/assets/brp_year_two.json
- ui/public/images/brp/brp_year_one.json
- ui/public/images/brp/brp_year_two.json
> GH-925 update BRP

- ui/src/components/events/EventCard.js
- ui/src/components/events/EventsPage.js
- ui/src/components/helpers/eventsHelpers.js
- ui/src/components/home/EventsSection.js
- ui/src/components/home/EventsSectionCards.js
Fix announcement logic, no date announcement will be shown in the back (Fixed logic to handle multiple no date announcements). Announcements will be sorted from newest dates.
A duplicate from #928
> GH-1: hotfix announcements

- ui/src/components/easter-2024/EasterContainer.js
- ui/src/components/easter-2024/EasterEvents.js
- ui/src/components/easter-2024/EasterMore.js
- ui/src/components/easter-2024/EasterStory.js
- Made sure UI is consistent across components (button radius, border thickness, spacing between bentos, etc.)
> GH-943: Easter UI Fixes

- ui/src/components/easter-2024/EasterEvents.js
- ui/src/components/easter-2024/EasterStory.js
> GH-1: Hotfix Easter

- server/api/controllers/forms/get-signedup-form.js
- server/api/controllers/forms/get-unsignedup-form.js
- ui/src/components/userProfile/UserProfileDesktop.js
- ui/src/components/userProfile/UserProfileMobile.js
Checks if previous submission of form is within validity period to allow users to re sign up on forms that are reopened.
> GH-935: Form Validity Period 

- server/api/controllers/forms/get-signedup-form.js
- server/api/controllers/forms/get-unsignedup-form.js
- ui/src/components/userProfile/UserProfileDesktop.js
- ui/src/components/userProfile/UserProfileMobile.js
Reverts hmcc-global/hmcchk-web#976
> Revert "GH-935: Form Validity Period "

- server/api/controllers/leadershipTeam/update-leadership-team.js
- ui/src/components/admin/leadershipTeam/AdminLeadershipTeamContainer.js
- ui/src/components/admin/leadershipTeam/LeadershipTeamGrid.js
After https://github.com/hmcc-global/hmcchk-web/pull/979 is merged, then can merge this
> GH-939: LG leaders frontend

- server/api/controllers/forms/get-signedup-form.js
- server/api/controllers/forms/get-unsignedup-form.js
- ui/src/components/userProfile/UserProfileDesktop.js
- ui/src/components/userProfile/UserProfileMobile.js
> GH-935: adjusted to check if last submission is within validity period

- ui/src/components/admin/announcements/AdminAnnouncementContainer.js
- ui/src/components/admin/announcements/AnnouncementEditorModal.js
- ui/src/components/helpers/components/FileUpload.js
It's finally here!!! Can upload image to our Wordpress, but need to update your .env to test this. I will upload new `/ui` env to our Discord in #database channel
> GH-929: Upload file to Wordpress component

- ui/package.json
- ui/src/components/forms/Form.js
- ui/src/components/forms/FormEditor.js
- ui/src/components/forms/FormField.js
- ui/src/components/forms/class/FormField.js
- ui/yarn.lock
Part 1:
- Replaced objects for formfields with FormField class for consistency
- Reworked how prefillable form fields are stored 
- Adjusted UI to work with new data structures
Todo in part 2: implement ID functionality and conditional forms backend design
> GH-988: replace old way of managing fields with new formfield class.

- ui/src/components/helpers/eventsHelpers.js
- Fixed inconsistent date formatting in event section cards
> GH-1008: Event Card Date Formatting Fix

- ui/public/index.html
- ui/src/components/NavigationBar/MainMenu.js
- ui/src/components/NavigationBar/NavBar.js
- ui/src/components/connect-prayer/PrayerFLoatButton.js
- ui/src/components/connect/ExperienceHmcc.js
- ui/src/components/footer/ChurchAppDownloadButton.js
- ui/src/components/footer/FooterMobile.js
- ui/src/components/footer/LinkGrid.js
- ui/src/components/footer/SoapDownloadButton.js
- ui/src/components/footer/footerLinks.json
- ui/src/components/home/EventsSection.js
- ui/src/components/home/EventsSectionCards.js
- ui/src/components/home/HelloSermonSection.js
- ui/src/components/home/LifeGroupSection.js
- ui/src/components/home/PopupContainer.js
- ui/src/components/home/SaturateVisionSection.js
- ui/src/util/TrackingUtil.js
- Added Google Analytics 4 + Google Tag Manager for user analytics monitoring
- Added custom IDs to components for tracking
> GH-992: Google analytics

- server/api/controllers/forms/post-create-submission.js
- server/api/helpers/camelize.js
- server/api/helpers/forms/get-form-alert-recipients.js
- server/api/models/Form.js
- server/views/emails/form-notify-leader-success.ejs
- ui/src/components/forms/FormEditor.js
- ui/src/components/forms/FormEditorContainer.js
- ui/src/components/helpers/lists.js
> GH-1012: Add Form sign up alerts

- server/api/controllers/sermonNotesParent/get-sermon-notes-parent.js
- server/api/controllers/userSermonNotes/get-user-sermon-notes.js
- ui/package.json
- ui/src/components/MainContainer.js
- ui/src/components/admin/sermonNotes/AdminSermonNotesContainer.js
- ui/src/components/admin/sermonNotes/SermonNotesEditorModal.js
- ui/src/components/helpers/SermonNotes.js
- ui/src/components/helpers/TipTap/FillInBlank.js
- ui/src/components/helpers/TipTap/FontSizeExtension.js
- ui/src/components/helpers/TipTap/MenuBar.js
- ui/src/components/helpers/TipTap/TiptapOutput.js
- ui/src/components/helpers/TipTap/UserNotesExtension.js
- ui/src/components/helpers/TipTap/index.js
- ui/src/components/helpers/components/BibleVerseAccordion.js
- ui/src/components/sermon-notes/SermonNotesContainer.js
- ui/yarn.lock
> 1017 integrate editor to main web

- ui/src/components/admin/sermonNotes/AdminSermonNotesContainer.js
- ui/src/components/admin/sermonNotes/SermonNotesEditorModal.js
- ui/src/components/helpers/TipTap/MenuBar.js
- ui/src/components/helpers/TipTap/index.js
- ui/src/components/helpers/TipTap/styles.scss
- ui/src/components/sermon-notes/SermonNotesContainer.js
> GH-1017: add text styles for diff sn texts

- ui/src/components/sermon-notes/SermonNotesContainer.js
Design (Josiah)
•⁠  ⁠make the title in mobile centered
•⁠  ⁠Author and date font can be bigger
> GH 1060: Fix minor UI display of sermon notes

- server/config/policies.js
- ui/src/components/NavigationBar/NavBar.js
- ui/src/components/admin/sermonNotes/AdminSermonNotesContainer.js
- ui/src/components/helpers/SermonNotes.js
- ui/src/components/helpers/TipTap/UserNotesExtension.js
- ui/src/components/helpers/components/BibleVerseAccordion.js
- ui/src/components/sermon-notes/SermonNotesContainer.js
Bible verse (Richie)
User notes (Richie)
> 1061 fix sn editor tiptap extension bugs

- ui/src/components/events/EventsPage.js
- if displaystartdate is before today do not show event
- Resources are always displayed last
> GH-1058: events display

- ui/src/components/admin/sermonNotes/SermonNotesEditorModal.js
- ui/src/components/helpers/SermonNotes.js
- ui/src/components/helpers/TipTap/UserNotesExtension.js
- ui/src/components/helpers/TipTap/styles.scss
- ui/src/components/screens/ErrorPage.js
- ui/src/components/sermon-notes/SermonNotesContainer.js
> 1 sn hotfix

- ui/src/components/admin/leadershipTeam/LeadershipTeamGrid.js
Only show relevant leadershipTeams by default
> GH-1091: #1

- ui/src/components/saturate/SaturateGoals.js
- Fixed saturate page spelling "collborating" to collaborating
> GH-1: Saturate page spelling fix

- ui/src/components/sermons/CurrentSermon.js
- ui/src/components/sermons/OfflinePageTabs.js
- ui/src/components/sermons/SermonSeries.js
- ui/src/components/sermons/SermonSeriesCard.js
- ui/src/components/sermons/SermonSocialMediaButtons.js
- Fixed the scrolling for "More in Series"
- Added "Watch Now" button for the "Latest Sermon"
> GH-1147: Addressed Sermon Page Comments

- ui/src/components/connect/Faq.js
- ui/src/components/connect/LifeGroups.js
- ui/src/components/footer/Footer.js
- Change footer to 2025 
- Change LG signup link to https://bit.ly/LGSignup2024
> Change LG link and footer to 2025

- ui/src/components/events/EventCard.js
- ui/src/components/events/EventsPage.js
Applied the following edits:
1. Change background color to the newest design, align heading and subheading to left
2. Align filter button spacings and change the colors
3. Fixed margin/padding for buttons inside modal
4. Change modal into drawer for mobile
> GH-1145: Edits to events page

- ui/src/components/MainContainer.js
- ui/src/components/admin/harvest-games/AdminHarvestGamesContainer.js
- ui/src/components/harvest-games/HarvestGamesContainer.js
- Adding skeleton components and routes for HG 2025 dev work
> GH-1263: Adding HG-related basic components and routes
